#!/bin/sh
# Copyright 2002 Herbert Straub

if [ -f config.cache ]; then
	rm config.cache
fi
if [ -f Makefile ]; then
	make clean
fi

echo "autoreconf..."
autoreconf -i

echo "Next run ./configure"
echo "Next run make"
